//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.8000.
// 
namespace Sirius.Coletor.SiriusService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ISirius", Namespace="http://tempuri.org/")]
    public partial class SiriusService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SiriusService() {
            this.Url = "http://192.168.1.50/Hmlog/SiriusService.svc";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISirius/ListarFiliais", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ListarFiliais() {
            object[] results = this.Invoke("ListarFiliais", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginListarFiliais(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ListarFiliais", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndListarFiliais(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISirius/ListarInventariosPendentes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ListarInventariosPendentes() {
            object[] results = this.Invoke("ListarInventariosPendentes", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginListarInventariosPendentes(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ListarInventariosPendentes", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndListarInventariosPendentes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISirius/ListarDepositosPorFilial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ListarDepositosPorFilial(int codigoFilial, [System.Xml.Serialization.XmlIgnoreAttribute()] bool codigoFilialSpecified) {
            object[] results = this.Invoke("ListarDepositosPorFilial", new object[] {
                        codigoFilial,
                        codigoFilialSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginListarDepositosPorFilial(int codigoFilial, bool codigoFilialSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ListarDepositosPorFilial", new object[] {
                        codigoFilial,
                        codigoFilialSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndListarDepositosPorFilial(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISirius/ListarLocalizacaoPorDeposito", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ListarLocalizacaoPorDeposito(int codigoDeposito, [System.Xml.Serialization.XmlIgnoreAttribute()] bool codigoDepositoSpecified) {
            object[] results = this.Invoke("ListarLocalizacaoPorDeposito", new object[] {
                        codigoDeposito,
                        codigoDepositoSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginListarLocalizacaoPorDeposito(int codigoDeposito, bool codigoDepositoSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ListarLocalizacaoPorDeposito", new object[] {
                        codigoDeposito,
                        codigoDepositoSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndListarLocalizacaoPorDeposito(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISirius/RetornaQuantidadeProdutoCadastrados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RetornaQuantidadeProdutoCadastrados(out int RetornaQuantidadeProdutoCadastradosResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool RetornaQuantidadeProdutoCadastradosResultSpecified) {
            object[] results = this.Invoke("RetornaQuantidadeProdutoCadastrados", new object[0]);
            RetornaQuantidadeProdutoCadastradosResult = ((int)(results[0]));
            RetornaQuantidadeProdutoCadastradosResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRetornaQuantidadeProdutoCadastrados(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RetornaQuantidadeProdutoCadastrados", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void EndRetornaQuantidadeProdutoCadastrados(System.IAsyncResult asyncResult, out int RetornaQuantidadeProdutoCadastradosResult, out bool RetornaQuantidadeProdutoCadastradosResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            RetornaQuantidadeProdutoCadastradosResult = ((int)(results[0]));
            RetornaQuantidadeProdutoCadastradosResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISirius/ListarProdutos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ListarProdutos(int pagina, [System.Xml.Serialization.XmlIgnoreAttribute()] bool paginaSpecified, int registrosPorPagina, [System.Xml.Serialization.XmlIgnoreAttribute()] bool registrosPorPaginaSpecified) {
            object[] results = this.Invoke("ListarProdutos", new object[] {
                        pagina,
                        paginaSpecified,
                        registrosPorPagina,
                        registrosPorPaginaSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginListarProdutos(int pagina, bool paginaSpecified, int registrosPorPagina, bool registrosPorPaginaSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ListarProdutos", new object[] {
                        pagina,
                        paginaSpecified,
                        registrosPorPagina,
                        registrosPorPaginaSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndListarProdutos(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISirius/ListarOperadoresColetor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ListarOperadoresColetor() {
            object[] results = this.Invoke("ListarOperadoresColetor", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginListarOperadoresColetor(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ListarOperadoresColetor", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndListarOperadoresColetor(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISirius/ListarInventarioPorCodigo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ListarInventarioPorCodigo(int codigoInventario, [System.Xml.Serialization.XmlIgnoreAttribute()] bool codigoInventarioSpecified) {
            object[] results = this.Invoke("ListarInventarioPorCodigo", new object[] {
                        codigoInventario,
                        codigoInventarioSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginListarInventarioPorCodigo(int codigoInventario, bool codigoInventarioSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ListarInventarioPorCodigo", new object[] {
                        codigoInventario,
                        codigoInventarioSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndListarInventarioPorCodigo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISirius/ImportarInventario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ImportarInventario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string inventario, out int ImportarInventarioResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ImportarInventarioResultSpecified) {
            object[] results = this.Invoke("ImportarInventario", new object[] {
                        inventario});
            ImportarInventarioResult = ((int)(results[0]));
            ImportarInventarioResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginImportarInventario(string inventario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ImportarInventario", new object[] {
                        inventario}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndImportarInventario(System.IAsyncResult asyncResult, out int ImportarInventarioResult, out bool ImportarInventarioResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            ImportarInventarioResult = ((int)(results[0]));
            ImportarInventarioResultSpecified = ((bool)(results[1]));
        }
    }
}
