//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.5477
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.5477.
// 
namespace Sirius.Coletor.SiriusService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ISirius", Namespace="http://tempuri.org/")]
    public partial class SiriusService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SiriusService() {
            this.Url = "http://192.168.1.50/Hmlog/SiriusService.svc";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISirius/ListarFiliais", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ListarFiliais() {
            object[] results = this.Invoke("ListarFiliais", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginListarFiliais(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ListarFiliais", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndListarFiliais(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISirius/ListarInventariosPendentes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ListarInventariosPendentes() {
            object[] results = this.Invoke("ListarInventariosPendentes", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginListarInventariosPendentes(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ListarInventariosPendentes", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndListarInventariosPendentes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISirius/ListarDepositosPorFilial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ListarDepositosPorFilial(int codigoFilial, [System.Xml.Serialization.XmlIgnoreAttribute()] bool codigoFilialSpecified) {
            object[] results = this.Invoke("ListarDepositosPorFilial", new object[] {
                        codigoFilial,
                        codigoFilialSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginListarDepositosPorFilial(int codigoFilial, bool codigoFilialSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ListarDepositosPorFilial", new object[] {
                        codigoFilial,
                        codigoFilialSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndListarDepositosPorFilial(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISirius/ListarLocalizacaoPorDeposito", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ListarLocalizacaoPorDeposito(int codigoDeposito, [System.Xml.Serialization.XmlIgnoreAttribute()] bool codigoDepositoSpecified) {
            object[] results = this.Invoke("ListarLocalizacaoPorDeposito", new object[] {
                        codigoDeposito,
                        codigoDepositoSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginListarLocalizacaoPorDeposito(int codigoDeposito, bool codigoDepositoSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ListarLocalizacaoPorDeposito", new object[] {
                        codigoDeposito,
                        codigoDepositoSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndListarLocalizacaoPorDeposito(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISirius/ListarTodosProdutos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ListarTodosProdutos() {
            object[] results = this.Invoke("ListarTodosProdutos", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginListarTodosProdutos(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ListarTodosProdutos", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndListarTodosProdutos(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISirius/ListarOperadoresColetor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ListarOperadoresColetor([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string tagColletor) {
            object[] results = this.Invoke("ListarOperadoresColetor", new object[] {
                        tagColletor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginListarOperadoresColetor(string tagColletor, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ListarOperadoresColetor", new object[] {
                        tagColletor}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndListarOperadoresColetor(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISirius/ListarInventarioPorCodigo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ListarInventarioPorCodigo(int codigoInventario, [System.Xml.Serialization.XmlIgnoreAttribute()] bool codigoInventarioSpecified) {
            object[] results = this.Invoke("ListarInventarioPorCodigo", new object[] {
                        codigoInventario,
                        codigoInventarioSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginListarInventarioPorCodigo(int codigoInventario, bool codigoInventarioSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ListarInventarioPorCodigo", new object[] {
                        codigoInventario,
                        codigoInventarioSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndListarInventarioPorCodigo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
